homepage: home

types:
  article:
    label: Artículo
    metadata: [resume]
  project:
    label: Proyecto
    metadata: [url]
  event:
    label: Evento
    metadata: [resume, date, lat, lng]
  member:
    label: Miembro
    metadata: [url]