homepage: home

types:
  article:
    label: Artículo
    metadata: [resume]
#  slides:
#    label: Presentación
#    metadata: [author]
#  gallery:
#    label: Galeria
  project:
    label: Proyecto
    metadata: [url]
  event:
    label: Evento
    metadata:
      resume: ~
      date: datetime
      lat: ~
      lng: ~
  member:
    label: Miembro
    metadata: [url]