homepage: 2

types:
  article:
    label: Articulo
    metadata: [resume]
  page:
    label: Página
  project:
    label: Proyecto
    metadata: [url]
  event:
    label: Evento
    metadata: [date, lat, long]
  member:
    label: Miembro
    metadata: [url]