# orden de más específico al más general (page debe estar al final ya que 
# tiene el match más genérico)
_admin:
    resource: "@AqpglugCodemedoBundle/Controller/AdminController.php"
    type:     annotation

_project:
    resource: "@AqpglugCodemedoBundle/Controller/ProjectController.php"
    type:     annotation

_article:
    resource: "@AqpglugCodemedoBundle/Controller/ArticleController.php"
    type:     annotation

_Event:
    resource: "@AqpglugCodemedoBundle/Controller/EventController.php"
    type:     annotation

_page:
    resource: "@AqpglugCodemedoBundle/Controller/PageController.php"
    type:     annotation
