parameters:
    codemedo.types.class:       Aqpglug\CodemedoBundle\Extension\Config
    codemedo.twig.class:        Aqpglug\CodemedoBundle\Extension\Twig

services:
    codemedo:
        class:        %codemedo.types.class%
    codemedo.twig:
        class:        %codemedo.twig.class%
        arguments:    [@codemedo]
        tags:
            -  { name: twig.extension }