parameters:
    codemedo.config.class:        Aqpglug\CodemedoBundle\Extension\Config
    codemedo.twig.class:          Aqpglug\CodemedoBundle\Extension\Twig
    codemedo.menu.class:          Aqpglug\CodemedoBundle\Extension\Menu

services:
    codemedo:
        class:        %codemedo.config.class%

    codemedo.twig:
        class:        %codemedo.twig.class%
        arguments:    [@codemedo]
        tags:
            -  { name: twig.extension }

    codemedo.menu:
        class:        %codemedo.menu.class%
        arguments:    [@codemedo, @router, @session]
        tags:
            -  { name: twig.extension }